import { readFileSync, writeFileSync } from 'fs';
const existing = JSON.parse(readFileSync('./data/npcs.json', 'utf8'));
let nextId = existing.length + 1;
const npc = (name, race, role, cls, appearance, personality, motivation, secret, cr, greeting, quest, farewell) => ({
    id: `npc-${String(nextId++).padStart(3, '0')}`,
    name, race, role, class: cls, appearance,
    personality, motivation, secret, cr,
    dialogue: { greeting, quest, farewell }
});

const newNpcs = [
    // ═══ HALF-ELF (need 4 more) ═══
    npc("Lyria Dawnwhisper", "Half-Elf", "Quest Giver", "Diplomat",
        "A graceful woman with sun-kissed skin, pointed ears half-hidden by auburn waves, and diplomatic robes bearing two nations' crests.",
        ["Diplomatic", "Idealistic", "Secretly lonely"],
        "Broker peace between the elven enclave and human settlement before war erupts",
        "She's the illegitimate daughter of the elven king — if exposed, both sides would reject her",
        4,
        "Greetings, travelers. I represent both sides of a conflict that neither side believes can be resolved. I'm hoping you can prove them wrong.",
        "The elven delegation arrives in three days. The humans are arming for war. I need you to recover a stolen heirloom — a peace offering that vanished from my quarters last night. Without it, negotiations collapse.",
        "You carry the hopes of two peoples. No pressure. And please... be discreet about my involvement."
    ),
    npc("Caelum Stormborne", "Half-Elf", "Antagonist", "Sorcerer",
        "Wild silver hair crackling with static, heterochromatic eyes — one green, one stormy grey — and arcane tattoos that pulse with lightning.",
        ["Volatile", "Brilliant", "Deeply resentful of being rejected by both peoples"],
        "Tear down the barriers between races by demonstrating their shared weakness",
        "His powers are slowly killing him — each spell shortens his lifespan by days",
        6,
        "Ah, more heroes come to stop the scary half-breed. How refreshingly predictable. Tell me — which half of me offends you more?",
        "I'm going to show this world what happens when you reject someone powerful enough to break it. The storm I'm building will level the walls between human and elf — literally.",
        "Run along now. When the skies darken, remember: I gave you a chance to join me."
    ),
    npc("Thessaly Moonvale", "Half-Elf", "Ally", "Bard / Healer",
        "Warm brown skin with faint freckles, braided dark hair woven with silver bells, and a lute carved from white birch. Her singing voice can literally mend wounds.",
        ["Empathetic", "Courageous", "Hides pain behind music"],
        "Record the true history of the conflict, not the propaganda both sides spread",
        "She was cursed — she can heal others but never herself",
        3,
        "Every wound tells a story, and I collect them all. Let me hear yours — and maybe I can help write a better ending.",
        "There's a village caught in the crossfire. Neither army claims them, so neither protects them. I can heal their wounded, but I can't fight off raiders alone.",
        "Stay safe. And if you hear a melody on the wind tonight, don't worry — it's just me, patching up the world one song at a time."
    ),
    npc("Fenwick Greenbough", "Half-Elf", "Neutral", "Ranger / Herbalist",
        "Lean and weathered with moss-green eyes, a longbow of yew, and a leather satchel overflowing with dried herbs. Smells perpetually of pine and sage.",
        ["Reclusive", "Practical", "Uncomfortable with emotions"],
        "Catalog every medicinal plant in the realm before logging destroys the old forests",
        "He discovered a plant that grants temporary immortality but buried the samples, fearing the consequences",
        3,
        "You're trampling my feverfew. Step to the left. No, YOUR left. ...Fine, just don't move at all.",
        "There's a grove deep in the Thornwood where a rare moonpetal grows — the only cure for the plague spreading in the lowlands. Problem is, something moved into the grove. Something territorial.",
        "Take these poultices. Apply to wounds, NOT to food. A previous client made that mistake. He survived, but his taste buds didn't."
    ),

    // ═══ DWARF (need 4 more) ═══
    npc("Durak Embervein", "Dwarf", "Quest Giver", "Cleric of the Forge",
        "A broad dwarf with a beard braided with copper wire, burn scars covering both forearms, and eyes that glow faintly orange when he prays.",
        ["Devout", "Stubborn", "Generous with those who earn respect"],
        "Reclaim a holy forge lost to duergar raiders and reignite its sacred flame",
        "He hears his god's voice less and less — fears the sacred flame is dying",
        5,
        "The forge speaks to those who listen. Today it speaks of you. Sit. Share an ale. Then we talk about what needs hammering.",
        "The Deep Forge of Anvarak was overrun sixty years ago. My order has tried three expeditions. None returned. But the sacred flame still burns — I can feel it. This time, we go with outsiders. Fresh eyes, fresh tactics.",
        "May your steel stay true. If you find the forge, do NOT touch the central anvil until I arrive. The consequences would be... explosive."
    ),
    npc("Brunhild Stonemantle", "Dwarf", "Ally", "Fighter / Shield Maiden",
        "A muscular dwarven woman with ice-blonde braids, a tower shield taller than she is, and a no-nonsense expression carved from granite.",
        ["Fearless", "Protective", "Has a dry wit sharper than her axe"],
        "Prove that dwarven shield maidens are the equal of any warrior in the realm",
        "She was exiled from her clan for refusing an arranged marriage — fights to reclaim her honor",
        5,
        "You need a shield wall? You've got one. Point me at the problem and stay behind me.",
        "My clan's hold is under siege from below — duergar tunneling up through the foundations. My family exiled me, but I won't let them die for pride. Help me break the siege, and I'll owe you a life-debt.",
        "Fight's over. You didn't embarrass yourself. That's high praise from a Stonemantle. Let's drink."
    ),
    npc("Torgan Alebeard", "Dwarf", "Neutral", "Innkeeper / Brewmaster",
        "Round-bellied with a magnificent brown beard stained with hops, perpetually ruddy cheeks, and thick fingers surprisingly delicate with a tap handle.",
        ["Jovial", "Perceptive", "Knows everyone's business"],
        "Brew the perfect ale — a recipe lost when his grandfather's brewery burned down",
        "His cellar connects to ancient dwarf tunnels he hasn't fully explored — things come up at night",
        1,
        "Welcome to the Stout and Stone! First round's on me if you've got a good story. Bad stories cost double.",
        "I need a favor. Something's been getting into my cellar. Not rats — something BIGGER. The tunnels under this place go deep, and lately, I hear... singing. Dwarven singing. From below. My grandfather's been dead forty years.",
        "Your tab's clear. And take a keg for the road — my latest batch. If you survive whatever you're walking into, I want honest feedback."
    ),
    npc("Helga Runechisel", "Dwarf", "Antagonist", "Artificer / Arms Dealer",
        "Wiry and sharp-eyed with close-cropped iron hair, runic tattoos on her knuckles, and a mechanical arm that whirs and clicks with every gesture.",
        ["Calculating", "Amoral about who buys her weapons", "Fiercely intelligent"],
        "Build the ultimate weapon — she doesn't care who commissions it",
        "Her mechanical arm contains a prototype doomsday device she can't control",
        7,
        "Ah, customers. Or are you here to lecture me about 'responsible crafting'? Save it. I make tools. What you do with them is your problem.",
        "I've been hired to build a siege weapon for someone you probably wouldn't approve of. But here's the thing — they also hired mercenaries to ensure I don't sell to anyone else. Those mercenaries are becoming a problem for my OTHER customers. Handle them, and I'll give you first pick of my inventory.",
        "Business is business. Don't take it personally. And don't touch the arm — last person who did lost three fingers."
    ),

    // ═══ HALFLING (need 3 more) ═══
    npc("Rosalind Thistledown", "Halfling", "Quest Giver", "Mayor",
        "A tiny but commanding halfling woman with silver spectacles, a perfectly pressed waistcoat, and a brass pocket watch she checks obsessively.",
        ["Organized", "Anxious", "Deeply protective of her community"],
        "Keep her village safe from the growing threats that the 'big folk' cities keep ignoring",
        "She's been secretly paying protection money to a bandit lord to keep the village safe",
        1,
        "You must be the adventurers. Thank goodness. Please, wipe your boots and come in. I have tea, maps, and very bad news. In that order.",
        "Caravans have stopped coming through. The bridge east of town was destroyed, and something is lurking in the ruins of the old mill. My constable investigated. She hasn't come back. I'm running out of people to send.",
        "Bring my constable home. And if you must fight whatever's out there, try not to damage the mill too badly. We'll need it when this is over."
    ),
    npc("Jasper Quickfoot", "Halfling", "Antagonist", "Rogue / Crime Lord",
        "A dapper halfling in an expensive coat, with slicked-back auburn hair, a diamond stud earring, and a smile that never reaches his cold blue eyes.",
        ["Charming", "Ruthless", "Considers crime an art form"],
        "Build a criminal empire that spans every major city in the realm",
        "He's secretly the son of a respected judge — his crime empire is partly revenge for his father's hypocrisy",
        6,
        "Please, sit! Can I offer you wine? It's imported. Most things I own are... imported. From other people's collections.",
        "I have a problem — a rival organization is muscling into MY territory. I'm a reasonable businessman, but I can't have that. Eliminate their leadership, and I'll make sure certain doors open for you. Very profitable doors.",
        "Pleasure doing business. And remember — you never met me. I was never here. And this conversation? Never happened. *winks*"
    ),
    npc("Daisy Bramblefoot", "Halfling", "Ally", "Druid / Cook",
        "A plump, sun-freckled halfling with wildflower garlands in her curly brown hair, bare feet caked with garden soil, and an apron with potion-stained pockets.",
        ["Nurturing", "Fierce when protecting nature", "Makes everything into a food metaphor"],
        "Heal the blighted farmland threatening her community's food supply",
        "She accidentally awakened an ancient nature spirit while trying to heal the soil — it's now demanding tribute",
        3,
        "Oh! Visitors! You look half-starved. Sit down before you fall down. I'll have soup ready in five minutes and opinions ready in three.",
        "The crops are dying. Not from drought or disease — from something in the SOIL. It's spreading from the old barrow hill. I tried communing with the earth, and something answered. Something hungry. I need help feeding it before it feeds on the village.",
        "Take these seed cakes for the road. They're magically fortified — one will keep you full for a day. Don't ask what's in them. Seriously. Don't."
    ),

    // ═══ ELF (need 4 more) ═══
    npc("Aelindra Starweaver", "Elf", "Quest Giver", "Wizard / Lorekeeper",
        "An ancient elf with silver hair to her waist, luminous amber eyes, and robes embroidered with constellations that shift with the actual night sky.",
        ["Patient", "Cryptic", "Carries the weight of centuries of memory"],
        "Prevent a prophecy she witnessed 800 years ago from coming true in this generation",
        "She is the one who accidentally set the prophecy in motion centuries ago",
        9,
        "I have waited a very long time for you. Not you specifically — for someone to arrive at this precise moment. Time is a river, and you've just stepped into the current.",
        "Eight hundred years ago, I witnessed a star fall and read what it portended. That future is now. The seals I placed are breaking. I need you to reinforce three of them before the next moon.",
        "Go swiftly. The stars are not patient, even if I am."
    ),
    npc("Thalion Greenleaf", "Elf", "Ally", "Ranger / Scout",
        "Lean and hawk-eyed with dark green skin (wood elf), leaf-patterned leather armor, and a longbow that he carved from a tree he grew from a seedling.",
        ["Silent", "Loyal", "Struggles with the impatience of shorter-lived races"],
        "Protect the ancient forest borders from encroaching civilization",
        "He's been alive for 400 years and has watched three human kingdoms rise and fall — he's growing numb to loss",
        4,
        "...I've been watching you for two hours. You walk like a wounded elk. But you made it this far, so perhaps there's hope.",
        "Loggers are cutting deeper into the Verdant Reach each season. I could stop them with arrows, but my elder says we must try diplomacy first. I need someone the humans will listen to — someone who looks like them.",
        "You've earned the forest's trust. That's not given lightly. The trees will remember your names for a century."
    ),
    npc("Seraphine Duskmantle", "Elf", "Antagonist", "Warlock / Assassin",
        "Pale as moonlight with jet-black hair and pupilless violet eyes. Moves like liquid shadow. Her elven grace is weaponized into something terrifying.",
        ["Cold", "Methodical", "Believes she serves a higher justice"],
        "Assassinate the corrupt leaders who betrayed the elven court, regardless of collateral damage",
        "Her patron is a fey lord who is manipulating her targets to consolidate his own power",
        8,
        "You shouldn't be able to see me. Impressive. Or perhaps disappointing — it means my magic is slipping. Either way, we need to talk.",
        "There are five names on my list. Three deserve death. Two are... complicated. I've been contracted to eliminate all five, but I'm beginning to question my employer's motives. Help me investigate, and perhaps fewer people die than planned.",
        "I don't make friends. But I acknowledge debts. If you ever need someone to... solve a problem quietly, you know how to find me. Or rather, I'll find you."
    ),
    npc("Elowyn Brightwater", "Elf", "Neutral", "Artisan / Glassblower",
        "Delicate features with turquoise eyes, silver-blonde hair pinned with crystal clips, and hands that glow faintly when she works her craft. Perpetually dusted with glass powder.",
        ["Perfectionist", "Dreamy", "More comfortable with beauty than violence"],
        "Create a masterwork that captures starlight permanently — an artistic obsession consuming her life",
        "Her glass creations sometimes show visions of the future, but she's afraid to look",
        2,
        "Oh — I wasn't expecting company. Watch the glass shards on the floor. And the molten glass. And the torch. Actually, don't touch anything.",
        "I need sand from the Singing Dunes. Not ordinary sand — the kind that hums when moonlight hits it. It's the missing ingredient for my magnum opus. But the dunes are guarded by something that doesn't appreciate visitors.",
        "Thank you. If this works... well, you'll be the first to see it. Beauty like this should be shared."
    ),

    // ═══ HALF-ORC (need 4 more) ═══
    npc("Grasha Ironfang", "Half-Orc", "Quest Giver", "Chieftain",
        "Towering and scarred with a jagged tusk, close-cropped black hair, and a necklace of claw trophies. Wears practical hide armor reinforced with salvaged plate.",
        ["Strategic", "Honorable", "Tired of proving herself"],
        "Unite the fractured orc clans under a banner of cooperation rather than conquest",
        "She's dying of a slow poison administered by a rival chief — needs a cure before her enemies discover her weakness",
        6,
        "You approach Grasha's fire. Brave or stupid — Grasha will decide which after you speak.",
        "The clans are fracturing. Warlord Krusk gathers an army for a raid that will bring the human kingdoms down on ALL of us. Grasha needs proof of his betrayal — evidence he's allied with a demon. Bring it, and the clans unite under peace.",
        "You have Grasha's respect. That is not given freely. Go well, and know that if you call, Grasha's warriors answer."
    ),
    npc("Marcus Halfblood", "Half-Orc", "Ally", "Paladin",
        "A refined half-orc in polished silver armor, with neatly trimmed tusks, gentle brown eyes, and a holy symbol worn proudly. His shield bears dents from protecting others.",
        ["Noble", "Self-doubting", "Furious when innocents are threatened"],
        "Prove that heritage doesn't define destiny by becoming a beacon of justice",
        "He killed his own father — an orc warlord — to stop a massacre, and the guilt haunts him",
        5,
        "Well met, friends. If you fight for justice, you have my shield. If you fight for coin... I'll still probably help. I'm working on being less judgmental.",
        "A cult has been abducting people from the slums — people nobody misses. But I miss them. I've traced the disappearances to the old temple district. I can't go alone. My order won't sanction the investigation. Will you?",
        "You showed courage today. Real courage — not the reckless kind, the kind that costs something. I'm proud to have stood beside you."
    ),
    npc("Vorka Skullsplitter", "Half-Orc", "Antagonist", "Barbarian / Warlord",
        "Massive even by orc standards, with war paint covering half her face, a greataxe notched with kill marks, and a wolf-skull pauldron. Radiates controlled fury.",
        ["Fearsome", "Cunning despite appearances", "Respects strength above all"],
        "Carve out a homeland for her people through conquest — diplomacy has failed too many times",
        "She was once a peace advocate. The massacre of her village by humans turned her into a warlord.",
        7,
        "You stand in Vorka's path. Few survive that. Speak your purpose before Vorka decides yours.",
        "Your soft kingdoms sit on land that was ours before your grandparents drew breath. I'm taking it back. But I'm not unreasonable — I'll give you one chance to negotiate. Bring your leaders to the Bloodstone Mesa at the next full moon. If they don't come... I march.",
        "You have spine. Vorka respects that. But respect won't stop the tide. Prepare your people."
    ),
    npc("Dorn Gentlehand", "Half-Orc", "Neutral", "Monk / Herbalist",
        "A lean half-orc with shaved head, prayer beads around his wrists, and surprisingly gentle hands. Wears simple robes and carries no weapons — he IS the weapon.",
        ["Serene", "Philosophical", "Struggles with inner rage he's spent decades taming"],
        "Achieve perfect inner peace to prove that nature can be overcome through discipline",
        "He once killed twelve men in a berserker rage before his monastery took him in — he remembers every face",
        5,
        "...Peace be with you. Sit. Breathe. Whatever brought you here can wait for one calm breath. ...Good. Now speak.",
        "There is a disturbance in the mountain shrine — something is corrupting the meditation chambers. The monks have fled. I cannot — this is my home and my burden. I need help cleansing the corruption without destroying the shrine itself.",
        "Walk gently. The world breaks so easily, and we are all stronger than we know."
    ),

    // ═══ TIEFLING (need 4 more) ═══
    npc("Ashara Emberheart", "Tiefling", "Quest Giver", "Warlock / Scholar",
        "Deep purple skin with curving horns wrapped in gold filigree, a long spaded tail, and burning amber eyes. Dresses in scholarly robes despite her infernal appearance.",
        ["Intellectual", "Passionate", "Frustrated by prejudice"],
        "Prove that infernal heritage can be wielded for good by solving an ancient demonic puzzle",
        "Her patron is her own ancestor — a trapped demon who genuinely loves her but can't be trusted",
        6,
        "Please, don't reach for your weapon — I get enough of that from the general public. I'm Professor Ashara. I study demons so we can STOP them.",
        "There's a summoning circle beneath the old university. Someone activated it, and something is halfway through. I can reverse it, but I need components from the original binding — scattered across three locations that are, naturally, extremely dangerous.",
        "Knowledge is the only weapon that gets sharper the more you use it. Thank you for helping me prove that."
    ),
    npc("Crimson", "Tiefling", "Ally", "Fighter / Bodyguard",
        "Brick-red skin, broken horns filed to sharp points, a heavy scar across the bridge of her nose, and functional plate armor painted matte black. No nonsense, all business.",
        ["Loyal", "Taciturn", "Softer than she appears"],
        "Protect her current charge — a young noble — long enough for the kid to grow up safe",
        "She's a former gladiator slave. The noble family that bought her freedom is the one she now protects.",
        5,
        "I'm the one standing between my charge and everyone who wants them dead. So — are you threat or ally? Choose fast.",
        "Someone put a bounty on my noble. Fifty thousand gold. That kind of money draws serious killers. I need help tracking the source while I stay close. You find who's paying, I'll handle the rest.",
        "You're reliable. That's the highest compliment I give. Don't make me take it back."
    ),
    npc("Lazarus Vex", "Tiefling", "Antagonist", "Bard / Con Artist",
        "Charcoal skin with a devilish goatee, small elegant horns, and golden eyes that sparkle with mischief. Impeccably dressed in velvet and silk, dripping with stolen jewelry.",
        ["Theatrical", "Manipulative", "Genuinely funny despite being terrible"],
        "Pull off the greatest con in history — steal a kingdom through pure charisma",
        "He's actually a deposed tiefling prince reclaiming his family's throne through the only means left — deception",
        5,
        "My reputation precedes me? How embarrassing. Which reputation — the charming rogue, the dangerous criminal, or the surprisingly good dancer?",
        "I need a crew for a job. Not just any job — THE job. We're going to steal the Duke's crown during his own coronation ball. Yes, while he's wearing it. *pause* I see you have questions.",
        "What a show! *takes a bow* Same time next heist? I'll bring the costumes."
    ),
    npc("Mercy Shadowborn", "Tiefling", "Neutral", "Cleric of the Grave",
        "Ashen grey skin with tiny vestigial horn nubs, pure white eyes, and clerical vestments in black and silver. Carries a censer that smokes with ghostly blue incense.",
        ["Compassionate", "Morbid sense of humor", "Sees death as a kindness, not a tragedy"],
        "Ensure the dead rest peacefully and the undead are returned to their graves",
        "She can see ghosts constantly — they follow her everywhere, begging for help, and she's exhausted",
        4,
        "Don't mind the cold spot behind you. That's just Gerald. He's been dead for sixty years and still follows me around because I forgot to bless his cat.",
        "The cemetery is restless. Someone's been stealing bodies, and the spirits are FURIOUS. I can calm them temporarily, but unless we stop the grave robber, this entire district will be haunted by dawn.",
        "The dead thank you. Well, most of them. Some are still grumpy, but that's just how some people die."
    ),

    // ═══ GNOME (need 4 more) ═══
    npc("Professor Fizzwick Cogsworth", "Gnome", "Quest Giver", "Artificer / Inventor",
        "A tiny gnome with wild white hair standing on end, magnifying goggles with five different lenses, and a waistcoat with pockets full of ticking devices.",
        ["Manic genius", "Absent-minded", "Explodes things accidentally and on purpose"],
        "Complete his life's work: a flying machine powered by captured lightning",
        "His previous invention — a portal device — accidentally opened a rift that's slowly growing",
        4,
        "YES! Perfect timing! Hold this. Don't pull the pin. Why does it have a pin? Excellent question — I'll answer later if we survive!",
        "So, funny story — I may have accidentally torn a small hole in reality. Very small! Barely noticeable! Except it's getting bigger. I need three arcane crystals to seal it, and they're all in locations that are, to use a technical term, 'catastrophically dangerous.'",
        "It worked! We're not dead! I love it when that happens! Here, take this gadget as thanks. I'm sixty percent sure it won't explode!"
    ),
    npc("Willow Gemheart", "Gnome", "Ally", "Illusionist",
        "A young gnome with pink-streaked chestnut hair, mismatched earrings, and clothes that shimmer between colors. Her illusions leak when she's emotional.",
        ["Creative", "Anxious", "Sees beauty in unexpected places"],
        "Master her wild magic before it reveals secrets she's keeping for dangerous people",
        "She accidentally witnessed a murder and the killer knows her face — she's been hiding behind illusions ever since",
        3,
        "Oh! Sorry! That wall isn't real. Neither is the door. The floor IS real though. Probably. Let me check. ...Yes, the floor is real.",
        "I've been hiding from someone — someone dangerous. My illusions keep me safe, but they're getting harder to maintain. I saw something I shouldn't have, and now there's a contract on me. I need help dealing with the source, not just the symptoms.",
        "You're the first real people I've talked to in weeks. Everything else has been illusions. Even my breakfast. Don't ask."
    ),
    npc("Nix Tinkerblast", "Gnome", "Antagonist", "Artificer / Mad Scientist",
        "Wild-eyed with singed green hair, a cybernetic eye that whirs audibly, and a lab coat covered in chemical burns and arcane formulae.",
        ["Unhinged genius", "No moral boundaries", "Genuinely doesn't understand why others are afraid"],
        "Push the boundaries of magical science beyond what any responsible person would attempt",
        "Their experiments are slowly merging them with their creations — they're becoming something not entirely gnomish",
        7,
        "Visitors! How delightful! Please ignore the screaming — it's just Tuesday. Would you like to see my latest creation? It's ALIVE! Mostly!",
        "I need test subjects. WILLING test subjects! That's an important distinction — I've learned from past... complaints. My serum can grant incredible power, but there are MINOR side effects. Scales, extra limbs, occasional fire breath...",
        "Fascinating data! Simply FASCINATING! You may leave now. Unless you'd like to stay for Phase Two? No? Everyone says that."
    ),
    npc("Sage Bottlewick", "Gnome", "Neutral", "Alchemist / Healer",
        "A kindly old gnome with enormous round spectacles, a long white braid, and steady hands stained permanently blue from decades of potion-making.",
        ["Gentle", "Meticulous", "Worries about everyone"],
        "Develop a universal antidote that can cure any poison",
        "She's perfected the formula but it requires a component so rare that procuring it would endanger a protected species",
        2,
        "Come in, come in, mind the cat, mind the potions, mind the cat IN the potions — Whiskers, get OUT of there! Now then, what ails you?",
        "I'm so close to a breakthrough — a potion that neutralizes ANY poison. But the final ingredient, silverbloom pollen, only grows in the Moonshade Grotto. The fey who live there don't appreciate uninvited guests.",
        "Take these potions. The red one heals. The blue one cures poison. The green one... well, I'm still working on the green one. Best not to drink it yet."
    ),

    // ═══ AASIMAR (need 4 more) ═══
    npc("Auriel Dawnshield", "Aasimar", "Ally", "Paladin / Guardian",
        "Golden-bronze skin that emanates faint warmth, pure white hair cropped military-short, and luminous silver eyes. His armor seems to glow from within.",
        ["Righteous", "Burdened", "Kind to a fault"],
        "Protect a sacred artifact from those who would corrupt it, even at the cost of his own life",
        "The artifact is slowly corrupting HIM — his celestial radiance is dimming",
        7,
        "I sense darkness in your path. Not in you — ahead of you. I'm here to help, if you'll have me.",
        "The Beacon of Solace is weakening. It has held back a planar incursion for centuries, but something — or someone — is draining its power. I can no longer protect it alone. The attackers come in waves, each stronger than the last.",
        "Your courage renewed my faith. The light endures because people like you choose to carry it."
    ),
    npc("Cassius Nightfall", "Aasimar", "Antagonist", "Fallen Paladin / Death Knight",
        "Once-radiant features now ashen and cracked, with wings of tarnished black feathers and eyes that burn with dying golden light. His armor is magnificent but corrupted.",
        ["Tragic", "Wrathful", "Still follows a twisted code of honor"],
        "Drag the celestial realm down to experience mortal suffering — they abandoned him when he needed them most",
        "He can still be redeemed — the divine spark hasn't fully died, and he secretly hopes someone will save him from himself",
        10,
        "An angel falls, and the heavens say nothing. Tell me, hero — does your god answer when YOU call? Because mine stopped listening long ago.",
        "The celestials sit in their golden realm while mortals suffer and die. I prayed for help when my congregation was slaughtered. The answer was silence. Now I'll MAKE them answer.",
        "Strike me down if you can. But know this: I was once exactly like you. Faithful. Hopeful. I wonder... how long until your god abandons you too?"
    ),
    npc("Elara Sunsong", "Aasimar", "Quest Giver", "Cleric / Oracle",
        "Luminous dark skin with golden freckles like constellations, flowing white robes, and a blindfold embroidered with celestial symbols — she sees through divine sight.",
        ["Serene", "Prophetic", "Terrified of one specific vision she won't share"],
        "Guide the chosen heroes to fulfill a prophecy she's seen in fragments",
        "The prophecy shows the heroes succeeding OR failing based on one choice she can't identify — she's seen both outcomes and is terrified of influencing the wrong one",
        8,
        "I cannot see your faces, but I see your souls. They burn brightly. That gives me hope. Please — I have been waiting for you.",
        "I have seen fragments of what comes: a darkness beneath a mountain, a betrayal by a trusted friend, and a light that either saves or destroys everything. The visions are incomplete, and I dare not interpret them for you — your choices must be your own.",
        "Walk your path, heroes. I cannot walk it for you. But I will pray every step of the way."
    ),
    npc("Jorin Emberwing", "Aasimar", "Neutral", "Monk / Wanderer",
        "Copper skin with barely visible luminescent markings, shaved head with a golden halo tattoo, and simple traveling clothes. Concealed wings manifest only when he fights.",
        ["Humble", "Wandering", "Unsure of his divine purpose"],
        "Find meaning in mortal life rather than the celestial destiny he was born into",
        "He rejected his angelic guide and is now truly alone — an aasimar without a patron",
        5,
        "I'm just a traveler. ...Yes, I know I glow slightly. It's a medical condition. Of sorts.",
        "There's a monastery in the Valley of Echoes where I once trained. The monks have gone silent. I need to know they're safe, but the valley has been overrun by shadows that shouldn't exist in a place so holy.",
        "Perhaps purpose finds us rather than the other way around. Today, helping you felt like purpose. That's enough for now."
    ),

    // ═══ DRAGONBORN (new race, need 5) ═══
    npc("Kriv Argentscale", "Dragonborn", "Quest Giver", "Fighter / Clan Elder",
        "An aging silver dragonborn with tarnishing scales, deep amber eyes, and a commanding presence. Wears ceremonial armor etched with his clan's history.",
        ["Wise", "Stern", "Fiercely loyal to his clan"],
        "Recover a stolen dragon egg before it hatches in enemy hands",
        "The egg was sold by his own son, who has defected to a rival clan",
        6,
        "I don't waste words, and I don't waste time. Our clan faces extinction. If you value honor, listen. If you don't, leave now.",
        "An egg was taken from our hatchery — a silver dragon egg, the first in three generations. Without it, our bloodline ends. My scouts tracked it to the Ashfort Mercenary Company. They plan to sell it to a collector in three days.",
        "You carry our clan's future. Literally. If the egg is returned safely, you will be honorary kin. That is not an empty title."
    ),
    npc("Farideh Flamescale", "Dragonborn", "Ally", "Sorcerer / Sage",
        "A slender red dragonborn with brilliant scarlet scales, golden eyes, and a quiet intensity. Wears scholar's robes with scorch marks from wild magic surges.",
        ["Brilliant", "Cautious with her power", "Surprisingly warm once comfortable"],
        "Master her draconic sorcery before it consumes her from within",
        "Her magic is growing beyond her control — each surge brings her closer to a permanent transformation into something less humanoid",
        5,
        "Stay back. No, it's fine, I just — *hands spark* — sorry. Give me a moment. My magic gets... excitable around new people.",
        "I need to reach the Dragon's Archive — a library inside a dead volcano. The answers to controlling my bloodfire sorcery are there. But the path is guarded by feral dragonborn who've already lost the fight I'm fighting. I need protection, not just from them, but possibly from myself.",
        "You trusted me when I could barely trust myself. That means more than you know."
    ),
    npc("Bharash Ironmaw", "Dragonborn", "Antagonist", "Warlord / Conqueror",
        "A massive bronze dragonborn in spiked plate armor, with a jaw like a battering ram and lightning crackling between his teeth. Battle-scarred and proud of every mark.",
        ["Ambitious", "Strategic", "Believes might makes right but follows a warrior's code"],
        "Establish a dragonborn empire and reclaim the glory his people lost centuries ago",
        "He made a pact with an actual dragon — when the empire is built, the dragon intends to rule it",
        9,
        "You stand before Bharash Ironmaw, Conqueror of the Three Passes. Kneel, or present yourself as worthy of standing.",
        "Your little kingdoms squabble over scraps while a true civilization crumbles. The dragonborn were an empire once. We will be again. I offer you a chance to stand on the winning side. The alternative is... less comfortable.",
        "You have courage. Misguided courage, but courage nonetheless. We will meet again on the field, and I will honor your bravery with a clean death."
    ),
    npc("Sora Stormbreath", "Dragonborn", "Neutral", "Artisan / Jeweler",
        "A petite blue dragonborn with iridescent scales that shift from azure to sapphire, delicate claws perfect for fine work, and a jeweler's loupe permanently attached to one horn.",
        ["Perfectionist", "Gossipy", "Charges extra for rude customers"],
        "Create a crown worthy of reuniting the dragonborn clans",
        "She's discovered that certain gemstone combinations channel draconic magic — her jewelry is more powerful than anyone realizes",
        2,
        "Welcome! Don't breathe on the display cases — fingerprints are bad enough, but claw-prints are murder on glass. Now, what catches your eye?",
        "I create beautiful things. Someone is breaking them. Three of my commissioned pieces have been stolen, and each one was enchanted — in ways I haven't exactly advertised. If those enchantments are misused... let's say it would be very loud and very destructive.",
        "Exquisite work deserves exquisite payment. I'll extend a discount for the heroism. Five percent. Don't push it."
    ),
    npc("Ghesh Ashwalker", "Dragonborn", "Ally", "Cleric / Diplomat",
        "A white dragonborn with frost-touched scales and calm ice-blue eyes. Wears priestly robes in silver and white, with a diplomatic sash from three nations.",
        ["Patient", "Eloquent", "Burns with quiet anger at injustice"],
        "Mediate between the warring dragonborn clans before civil war destroys them all",
        "He's been secretly communicating with the 'enemy' clan leader — they're childhood friends trying to prevent war from both sides",
        5,
        "Words before swords. That is my creed. If you share it, please — let us talk.",
        "War is coming between the Ironmaw and Argentscale clans. I serve neither — I serve peace. There is a neutral meeting ground, the Accord Stones, where both sides have agreed to parley. I need escorts I can trust to not escalate an already volatile situation.",
        "Peace is fragile. It must be guarded as fiercely as any fortress. Thank you for guarding it today."
    ),

    // ═══ GOBLIN (need 3 more) ═══
    npc("Skrix the Resourceful", "Goblin", "Quest Giver", "Merchant / Scavenger",
        "A lean goblin in an oversized trench coat filled with pockets, each containing something questionable. Missing an ear, gained a crude mechanical replacement.",
        ["Enterprising", "Paranoid", "Weirdly honest for a goblin"],
        "Build a legitimate trading post that bridges goblin and non-goblin communities",
        "He's the deposed king of a goblin tribe — 'deposed' meaning 'narrowly escaped assassination'",
        2,
        "Psst! You looking to buy? Sell? Trade? Information? Skrix has it ALL. Mostly. Some of it might be slightly expired.",
        "Skrix has a problem. Skrix's old tribe found Skrix. They want Skrix dead — bad for business, worse for Skrix's health. But they're also sitting on a gold mine. Literal gold mine. Help Skrix deal with the leadership problem, Skrix splits the gold. Sixty-forty. Skrix gets sixty. Non-negotiable. ...Okay, fifty-fifty.",
        "Good doing business! Skrix remembers friends. Come back anytime — Skrix will have new inventory. Probably legal inventory!"
    ),
    npc("Nettle", "Goblin", "Ally", "Ranger / Beast Tamer",
        "A small goblin girl with oversized amber eyes, patched leather armor, and a dire weasel companion three times her size named 'Bitey.' Covered in animal fur and scratches.",
        ["Brave beyond her size", "Speaks mostly through her animals", "Trusts beasts over people"],
        "Create a sanctuary for abused and abandoned creatures",
        "Bitey is actually a polymorphed knight who was cursed — she doesn't know, but she'd be devastated to lose her best friend",
        3,
        "*A dire weasel hisses at you* Bitey says you're okay. Bitey's usually right. I'm Nettle. We help animals. You hurt any animals? ...Good. We'd have a problem.",
        "Bad people are trapping forest creatures for arena fights. ARENA FIGHTS! Bitey is VERY angry. Nettle is also angry but in a quieter way. We know where the fighting pits are. Need help breaking them. And the creatures inside? They come home with Nettle.",
        "Animals don't forget kindness. Neither does Nettle. If you need tracking, finding, or biting — Nettle and Bitey are there."
    ),
    npc("Grix Boomfizzle", "Goblin", "Neutral", "Alchemist / Pyromaniac",
        "A hyperactive goblin with wild orange hair (possibly from chemical exposure), goggles fused to face with alchemical residue, and bandoliers of questionable potions.",
        ["Chaotic", "Surprisingly knowledgeable about chemistry", "Addicted to explosions"],
        "Create the biggest, most beautiful explosion ever witnessed without killing anyone (this last part is new for Grix)",
        "He accidentally discovered a formula for a weapon of mass destruction and immediately forgot it — it's in his notes somewhere",
        3,
        "HELLO YES WELCOME watch your step there's a puddle of something DO NOT STEP IN THE PUDDLE — oh. Oh no. *ducks behind counter* ... ... okay we're fine. Fine! Welcome!",
        "Grix needs a thing. Specific thing. Dragon bile — very small amount! Just a teaspoon! For science! Definitely NOT for making a bomb — Grix is reformed! Mostly! The explosion will be CONTAINED this time! Promise! ...Probably!",
        "Here! Take this! *hands over smoking vial* It's a healing potion! ...Well, Grix is pretty sure it's a healing potion. If it's not, duck and cover."
    ),
];

const all = [...existing, ...newNpcs];
writeFileSync('./data/npcs.json', JSON.stringify(all, null, 2) + '\n');
console.log(`✅ Wrote ${all.length} NPCs (${existing.length} existing + ${newNpcs.length} new)`);

// Count by race
const byRace = {};
for (const n of all) { byRace[n.race] = (byRace[n.race] || 0) + 1; }
console.log('\nBy race:', byRace);

// Count by role
const byRole = {};
for (const n of all) { byRole[n.role] = (byRole[n.role] || 0) + 1; }
console.log('By role:', byRole);
